[project]
name = "day17-cohort4-nguyenphuongnam-2a202602869-memorysystems4agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.3",
    "langchain-anthropic>=1.7.5",
    "langchain-google-genai>=4.4.0",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.7",
    "langchain-openrouter>=0.2.9",
    "langgraph>=1.2.12",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
    "tabulate>=0.10.0",
]
